server:
  port: 8087
spring:
  session:
    store-type: redis
#TOKEN client
com:
  xu:
    myOAuth2Properties:
      MYOAuth2ClientProperties[1]:
        clientId: xuhongda
        clientSecret: 7777_a
        accessTokenValiditySeconds: 7777
      MYOAuth2ClientProperties[2]:
        clientId: yan
        clientSecret: 8888
        accessTokenValiditySeconds: 8888


