server:
  port: 8087
spring:
  session:
    store-type: redis
#TOKEN client


com:
  xu:
    myOauth2Properties:
      myOauth2ClientProperties[0]:
        clientId: reader
        clientSecret: noopsecret
      myOauth2ClientProperties[1]:
        clientId: yan
        clientSecret: 1212